## Casino Die Rolling

In [3]:
from datascience import *
import numpy as np

### Part 1:Set up die
---

In [6]:
die_faces = np.arange(1, 7)
print("Die faces:", die_faces)
print()

Die faces: [1 2 3 4 5 6]


### PART 2: SIMULATE 1000 GAMES
---

In [8]:
num_games = 1000

# Roll two dice by sampling from die_faces
die1 = np.random.choice(die_faces, num_games)
die2 = np.random.choice(die_faces, num_games)

# Calculate the sum
total = die1 + die2

# Win if sum equals 2 OR sum equals 12
win = (total == 2) | (total == 12)


### PART 3: BUILD THE GAMES TABLE
---

In [9]:
games = Table().with_columns(
    'Game', np.arange(1, num_games + 1),
    'Die 1', die1,
    'Die 2', die2,
    'Sum', total,
    'Win', win
)

print("First 10 games:")
games.show(10)
print()

First 10 games:


### PART 4: ADD PAYOUT COLUMNS
---

In [10]:
# Option A: 15:1 payout (Casino's offer)
# Win $15, Lose $1
payout_15to1 = win * 16 - 1

# Option B: 14:1 payout (Worse casino offer)
# Win $14, Lose $1
payout_14to1 = win * 15 - 1

# Option C: 17:1 payout (Fair odds)
# Win $17, Lose $1
payout_17to1 = win * 18 - 1

games = games.with_column('Payout 15:1', payout_15to1)
games = games.with_column('Payout 14:1', payout_14to1)
games = games.with_column('Payout 17:1', payout_17to1)

print("Games with payouts:")
games.show(10)
print()

Games with payouts:


### PART 5: ADD BANKROLL TRACKING
---

In [13]:
starting_bankroll = 100

# Calculate cumulative profit/loss for each payout option
cumulative_15to1 = np.cumsum(payout_15to1)
cumulative_14to1 = np.cumsum(payout_14to1)
cumulative_17to1 = np.cumsum(payout_17to1)

# Add starting bankroll to cumulative profit/loss
bankroll_15to1 = starting_bankroll + cumulative_15to1
bankroll_14to1 = starting_bankroll + cumulative_14to1
bankroll_17to1 = starting_bankroll + cumulative_17to1

games = games.with_column('Bankroll 15:1', bankroll_15to1)
games = games.with_column('Bankroll 14:1', bankroll_14to1)
games = games.with_column('Bankroll 17:1', bankroll_17to1)

print("Games with bankroll tracking:")
games.select('Game', 'Sum', 'Win', 'Payout 15:1', 'Bankroll 15:1').show(20)
print()

Games with bankroll tracking:


### PART 6: BASIC ANALYSIS
---

In [15]:
print("=" * 60)
print("BASIC STATISTICS")
print("=" * 60)

# How many wins?
num_wins = games.where('Win', True).num_rows
print(f"Number of wins: {num_wins} out of {num_games}")
print(f"Win rate: {num_wins/num_games:.1%}")
print(f"Theoretical win rate: {2/36:.1%} (or {1/18:.1%})")
print()

# Show all winning games
print("All winning games:")
games.where('Win', True).show()
print()

============================================================
BASIC STATISTICS
============================================================
Number of wins: 52 out of 1000
Win rate: 5.2%
Theoretical win rate: 5.6% (or 5.6%)

All winning games:


### PART 7: PAYOUT ANALYSIS
---

In [16]:
print("=" * 60)
print("PAYOUT ANALYSIS")
print("=" * 60)

avg_15to1 = np.mean(games.column('Payout 15:1'))
avg_14to1 = np.mean(games.column('Payout 14:1'))
avg_17to1 = np.mean(games.column('Payout 17:1'))

print(f"Average payout per game (15:1): ${avg_15to1:.3f}")
print(f"Average payout per game (14:1): ${avg_14to1:.3f}")
print(f"Average payout per game (17:1): ${avg_17to1:.3f}")
print()

total_15to1 = sum(games.column('Payout 15:1'))
total_14to1 = sum(games.column('Payout 14:1'))
total_17to1 = sum(games.column('Payout 17:1'))

print(f"Total profit/loss after {num_games} games:")
print(f"  15:1 payout: ${total_15to1:.2f}")
print(f"  14:1 payout: ${total_14to1:.2f}")
print(f"  17:1 payout: ${total_17to1:.2f}")
print()

============================================================
PAYOUT ANALYSIS
============================================================
Average payout per game (15:1): $-0.168
Average payout per game (14:1): $-0.220
Average payout per game (17:1): $-0.064

Total profit/loss after 1000 games:
  15:1 payout: $-168.00
  14:1 payout: $-220.00
  17:1 payout: $-64.00


### PART 8: BANKROLL ANALYSIS
---

In [17]:
print("=" * 60)
print("BANKROLL ANALYSIS")
print("=" * 60)

final_15to1 = bankroll_15to1[-1]
final_14to1 = bankroll_14to1[-1]
final_17to1 = bankroll_17to1[-1]

print(f"Starting bankroll: ${starting_bankroll:.2f}")
print(f"\nFinal bankroll after {num_games} games:")
print(f"  15:1 payout: ${final_15to1:.2f} (change: ${final_15to1 - starting_bankroll:.2f})")
print(f"  14:1 payout: ${final_14to1:.2f} (change: ${final_14to1 - starting_bankroll:.2f})")
print(f"  17:1 payout: ${final_17to1:.2f} (change: ${final_17to1 - starting_bankroll:.2f})")
print()

# Maximum and minimum bankrolls
max_15to1 = max(bankroll_15to1)
min_15to1 = min(bankroll_15to1)

print(f"Bankroll range (15:1 payout):")
print(f"  Maximum: ${max_15to1:.2f}")
print(f"  Minimum: ${min_15to1:.2f}")
print()

# Did we go broke?
broke_15to1 = min_15to1 <= 0
if broke_15to1:
    # Find when we went broke
    broke_game = np.where(bankroll_15to1 <= 0)[0][0] + 1
    print(f"⚠️  You went broke at game #{broke_game}!")
else:
    print(f"✓ You never went broke (minimum was ${min_15to1:.2f})")
print()

============================================================
BANKROLL ANALYSIS
============================================================
Starting bankroll: $100.00

Final bankroll after 1000 games:
  15:1 payout: $-68.00 (change: $-168.00)
  14:1 payout: $-120.00 (change: $-220.00)
  17:1 payout: $36.00 (change: $-64.00)

Bankroll range (15:1 payout):
  Maximum: $115.00
  Minimum: $-72.00

⚠️  You went broke at game #548!

### PART 9: THEORETICAL VS ACTUAL
---

In [18]:
print("=" * 60)
print("THEORY VS REALITY")
print("=" * 60)

# Theoretical expected values
prob_win = 2/36

ev_15to1 = (15 * prob_win) + (-1 * (1 - prob_win))
ev_14to1 = (14 * prob_win) + (-1 * (1 - prob_win))
ev_17to1 = (17 * prob_win) + (-1 * (1 - prob_win))

print("THEORETICAL Expected Value per game:")
print(f"  15:1 payout: ${ev_15to1:.4f}")
print(f"  14:1 payout: ${ev_14to1:.4f}")
print(f"  17:1 payout: ${ev_17to1:.4f}")
print()

print("YOUR ACTUAL Average per game:")
print(f"  15:1 payout: ${avg_15to1:.4f}")
print(f"  14:1 payout: ${avg_14to1:.4f}")
print(f"  17:1 payout: ${avg_17to1:.4f}")
print()

print("Difference (should be small with more games):")
print(f"  15:1 difference: ${abs(ev_15to1 - avg_15to1):.4f}")
print(f"  14:1 difference: ${abs(ev_14to1 - avg_14to1):.4f}")
print(f"  17:1 difference: ${abs(ev_17to1 - avg_17to1):.4f}")
print()

============================================================
THEORY VS REALITY
============================================================
THEORETICAL Expected Value per game:
  15:1 payout: $-0.1111
  14:1 payout: $-0.1667
  17:1 payout: $0.0000

YOUR ACTUAL Average per game:
  15:1 payout: $-0.1680
  14:1 payout: $-0.2200
  17:1 payout: $-0.0640

Difference (should be small with more games):
  15:1 difference: $0.0569
  14:1 difference: $0.0533
  17:1 difference: $0.0640

## PART 10: HOUSE EDGE EXPLANATION
---

In [19]:
print("=" * 60)
print("WHY CASINOS WIN - THE HOUSE EDGE")
print("=" * 60)

print(f"Probability of winning: {prob_win:.4f} or {prob_win:.1%}")
print(f"True odds against you: 17 to 1")
print()

print("Fair payout (17:1):")
print(f"  Expected value: ${ev_17to1:.4f} per game")
print(f"  Over {num_games} games: ${ev_17to1 * num_games:.2f}")
print(f"  ✓ Break even in the long run!")
print()

print("Casino payout (15:1):")
print(f"  Expected value: ${ev_15to1:.4f} per game")
print(f"  Over {num_games} games: ${ev_15to1 * num_games:.2f}")
print(f"  House edge: {abs(ev_15to1):.4f} per game or {abs(ev_15to1/(1+15)*100):.2f}%")
print()

print("Worse casino payout (14:1):")
print(f"  Expected value: ${ev_14to1:.4f} per game")
print(f"  Over {num_games} games: ${ev_14to1 * num_games:.2f}")
print(f"  House edge: {abs(ev_14to1):.4f} per game or {abs(ev_14to1/(1+14)*100):.2f}%")
print()

============================================================
WHY CASINOS WIN - THE HOUSE EDGE
============================================================
Probability of winning: 0.0556 or 5.6%
True odds against you: 17 to 1

Fair payout (17:1):
  Expected value: $0.0000 per game
  Over 1000 games: $0.00
  ✓ Break even in the long run!

Casino payout (15:1):
  Expected value: $-0.1111 per game
  Over 1000 games: $-111.11
  House edge: 0.1111 per game or 0.69%

Worse casino payout (14:1):
  Expected value: $-0.1667 per game
  Over 1000 games: $-166.67
  House edge: 0.1667 per game or 1.11%


### PART 11: DISTRIBUTION OF SUMS
---

In [21]:
print("=" * 60)
print("DISTRIBUTION OF DICE SUMS")
print("=" * 60)

sum_distribution = games.group('Sum')
sum_distribution.show()
print()

============================================================
DISTRIBUTION OF DICE SUMS
============================================================


## PART 12: SAMPLE BANKROLL TRAJECTORY
---

In [23]:
print("=" * 60)
print("BANKROLL OVER TIME (every 50 games)")
print("=" * 60)

trajectory = games.take(np.arange(0, num_games, 50))
trajectory.select('Game', 'Win', 'Bankroll 15:1', 'Bankroll 14:1', 'Bankroll 17:1').show()

============================================================
BANKROLL OVER TIME (every 50 games)
============================================================